var index = '<!doctype html>';
index +='<html lang="en">';
index +='<head>';
index +='	<!-- Required meta tags -->';
index +='	<meta charset="utf-8">';
index +='	<meta name="viewport" content="width=device-width, initial-scale=1">';
index +='	<!-- Bootstrap CSS -->';
index +='	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">';
index +='	<title>Hello, world!</title>';
index +='</head>';
index +='	<body>';
index +='		<h1>Hello, world!</h1>';
index +='		<!-- Optional JavaScript; choose one of the two! -->';
index +='		<!-- Option 1: Bootstrap Bundle with Popper -->';
index +='		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>';
index +='		<!-- Option 2: Separate Popper and Bootstrap JS -->';
index +='		<!--<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">';
index +='		</script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>-->';
index +='	</body>';
index += '</html>';
index += "Ole pelota otra vez";
export var index;